# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: publish on release

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - run: yarn install --frozen-lockfile
      - run: yarn test ui
      - run: yarn build ui
      - run: cd ${GITHUB_WORKSPACE}/dist/libs/ui
      - run: yarn publish --new-version ${GITHUB_REF#"refs/tags/"}
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
